config/routes.rb
Rails.application.routes.draw do

  root 'borrows#index'
  resources :borrows
  resources :users do
    collection do
      get :totals
    end
  end
  

end

app/models/borrow.rb
class Borrow < ActiveRecord::Base
  validates :borrower_id, presence: true, allow_nil: false
  validates :borrowing_id, presence: true, allow_nil: false
  validate { errors.add(:base, 'Borrower and Borrowing must be different!') if borrower_id == borrowing_id }
  validates :amount, presence: true, allow_nil: false, numericality: { greater_than: 0 }
  # validates :comment
  validates :date, presence: true, allow_nil: false
  # validates :repaid

  belongs_to :borrowing, class_name: "User"
  belongs_to :borrower, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, allow_nil: false, uniqueness: true, length: { minimum: 3, maximum: 100 }
  
  # TODO wirklich destroy - sollen Borrows gelöscht werden, wenn ein User gelöscht wird?
  has_many :active_borrows, class_name: "Borrow", foreign_key: "borrower_id", dependent: :destroy
  has_many :passive_borrows, class_name: "Borrow", foreign_key: "borrowing_id", dependent: :destroy
  
  def borrow(other_user, amount, comment, date)
    active_borrows.create(borrowing_id: other_user.id, amount: amount, comment: comment, date: date, repaid: false)
  end
  
  def unborrow(id)
    active_borrows.find_by(id: id).destroy
  end

  def borrows_to(other_user)
    active_borrows.where(repaid: false).where(borrowing: other_user)
  end

  def borrowing_from(other_user)
    passive_borrows.where(repaid: false).where(borrower: other_user)
  end

  def borrows_to_sums
    active_borrows.where(repaid:false).group('borrowing').sum(:amount)
  end

  def borrowing_from_sums
    passive_borrows.where(repaid: false).group('borrower').sum(:amount)
  end

  def totals
    t = Hash.new(0)
    # negative values imply that the other user borrowes more
    # to this user than this user borrowed from the other user
    borrows_to_sums.each do |user, sum|
      t[user] += sum
    end
    borrowing_from_sums.each do |user, sum|
      t[user] -= sum
    end
    # if amount is zero, remove this entry
    t.reject { |user, sum| sum == 0 }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  # TODO before_actions for certain actions? requires implementation of authentication
  
  def index
    @user_options = User.all.map { |a| [ a.name, a.id ] }

    # filter by borrower or borrowing, if given
    scope = Borrow
    if (params[:borrower].present?)
      scope = scope.where("borrower_id = ?", params[:borrower])
    end
    if (params[:borrowing].present?)
      scope = scope.where("borrowing_id = ?", params[:borrowing])
    end
    if (!params[:repaid].present?)
      scope = scope.where.not(repaid: true)
    end
    @borrows = scope.all.paginate(page: params[:page])
  end

  def show
    @borrow = Borrow.find_by(id: params[:id])
  end

  def new
    @borrow = Borrow.new
    @borrow.date = Time.zone.now
  end

  def create
    @borrower = User.find_by(id: params[:borrow][:borrower_id])
    @borrow = @borrower.active_borrows.build(safe_params)
    @borrow.repaid = false
    if @borrow.save
      flash[:success] = "Borrow created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @borrow = Borrow.find_by(id: params[:id])
  end

  def update
    @borrow = Borrow.find_by(id: params[:id])
    if @borrow.update_attributes(safe_params)
      flash[:success] = "Borrow updated!"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    Borrow.find_by(id: params[:id]).destroy
    flash[:success] = "Borrow destroyed!"
    redirect_to borrows_url
  end
  
  private
  
    def safe_params
      params.require(:borrow).permit(:borrower_id, :borrowing_id, :amount, :date, :comment, :repaid)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # TODO before_actions for certain actions? requires implementation of authentication

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find_by(id: params[:id])
    @sums_to = @user.borrows_to_sums
    @sums_from = @user.borrowing_from_sums
    @totals = @user.totals
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(safe_params)
    if @user.save
      flash[:success] = "User created!"
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(safe_params)
      flash[:success] = "User updated!"
      redirect_to users_url
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "User destroyed!"
    redirect_to users_url
  end
  
  # TODO warum kein eigener controller?
  def totals
    @totals = Hash.new(0)
    # TODO repaid rein
    Borrow.all.each do |b|
      @totals[b.borrower] -= b.amount
      @totals[b.borrowing] += b.amount
    end
    @totals = @totals.reject { |user, amount| amount == 0 }
    # solve
    @solve = []
    t = @totals.clone
    while t.count > 0
      max_t = t.max_by { |user, amount| amount }
      min_t = t.min_by { |user, amount| amount }
      if max_t[1] + min_t[1] > 0
        @solve << { user_from: max_t[0], user_to: min_t[0], amount: -min_t[1] }
        t[max_t[0]] += min_t[1]
        t[min_t[0]] = 0
      else
        @solve << { user_from: max_t[0], user_to: min_t[0], amount: max_t[1] }
        t[min_t[0]] += max_t[1]
        t[max_t[0]] = 0
      end
      t = t.reject { |user, amount| amount == 0 }
    end
  end
  
  private
  
    def safe_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_link(user)
    link_to user.name, user
  end
end

app/views/borrows/_borrow_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @borrow, html: { class: "form-horizontal" } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <div class="form-group">
        <%= f.label :borrower, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.collection_select :borrower_id, User.all, :id, :name, {}, class: 'form-control' %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :borrowing, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.collection_select :borrowing_id, User.all, :id, :name, {}, class: 'form-control' %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :amount, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :amount, class: 'form-control' %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :date, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.date_field :date, class: 'form-control',
            value: !@borrow.date.nil? ? @borrow.date.to_formatted_s(:daymonthyear) : nil %>
        </div>
      </div>
    
      <div class="form-group">
        <%= f.label :comment, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_area :comment, class: 'form-control' %>
        </div>
      </div>

      <% if @show_repaid_checkbox %>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :repaid %> Repaid
              </label>
            </div>
          </div>
        </div>
        <% end %>
    
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit @submit_text, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/borrows/edit.html.erb
<h1>Borrows</h1>

<%= render 'shared/subnav', model: :borrow, var: @borrow %>

<% @submit_text = "Update borrow" %>
<% @show_repaid_checkbox = true %>
<%= render 'borrow_form' %>

app/views/borrows/index.html.erb
<h1>Borrows</h1>

<%= render 'shared/subnav', model: :borrow %>

<%= will_paginate @borrows, class: "pagination-container" %>

<div class="list-group">
  <%= form_tag '', method: :get, class: "form-inline list-group-item" do %>
    <div class="form-group">
      <%= label_tag :borrower %>
      <%= select_tag :borrower, options_for_select(@user_options, params[:borrower]), class: 'form-control', onchange: "this.form.submit();", include_blank: '(all)' %>
    </div>
    <div class="form-group">
      <%= label_tag :borrowing %>
      <%= select_tag :borrowing, options_for_select(@user_options, params[:borrowing]), class: 'form-control', onchange: "this.form.submit();", include_blank: '(all)' %>
    </div>
    <div class="checkbox">
      <label>
      <%= check_box_tag :repaid, 1, params[:repaid], onchange: "this.form.submit();" %> Show repaid
      </label>
    </div>
    <%= submit_tag "Filter", class: "btn btn-default" %>
  <% end %>
  <% if @borrows.any? %>
    <% @borrows.each do |borrow| %>
      <a class="list-group-item<% if borrow.repaid %> disabled<% end %>" href="<%= borrow_path borrow %>">
        <span class="borrow-date"><%= borrow.date.to_formatted_s(:daymonthyear) %></span>:
        <span class="borrower-name"><%= borrow.borrower.name %></span> borrowed
        <span class="borrowing-name"><%= borrow.borrowing.name %></span>
        <span class="borrow-amount"><%= borrow.amount %> EUR</span>
        <% if !borrow.comment.blank? %>for <span class="borrow-comment"><%= borrow.comment %></span><% end %>
      </a>
    <% end %>
  <% else %>
    <p>No borrows found.</p>
  <% end %>
</div>

<%= will_paginate @borrows, class: "pagination-container" %>

app/views/borrows/new.html.erb
<h1>Borrows</h1>

<%= render 'shared/subnav', model: :borrow %>

<% @submit_text = "Create borrow" %>
<% @show_repaid_checkbox = false %>
<%= render 'borrow_form' %>

app/views/borrows/show.html.erb
<h1>Borrows</h1>

<%= render 'shared/subnav', model: :borrow, var: @borrow %>

<dl class="dl-horizontal">
  <dt>Borrower</dt>
  <dd><%= user_link @borrow.borrower %></dd>
  <dt>Borrowing</dt>
  <dd><%= user_link @borrow.borrowing %></dd>
  <dt>Amount</dt>
  <dd><%= @borrow.amount %> EUR</dd>
  <dt>Date</dt>
  <dd><%= @borrow.date.to_formatted_s(:daymonthyear) %></dd>
  <dt>Comment</dt>
  <dd><%= @borrow.comment %></dd>
  <dt>Repaid</dt>
  <dd><%= @borrow.repaid ? 'Yes' : 'No' %></dd>
</dl>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Borrow App</small>
  <nav>
    <ul>
      <li><a href="#top">Top</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topnavbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "borrow app", root_path, id: 'logo' %>
    </div>
    <div class="collapse navbar-collapse" id="topnavbar">
      <ul class="nav navbar-nav navbar-right">
        <li<% if controller.controller_name == 'borrows' %> class="active"<% end %>><%= link_to "Borrows", borrows_path %></li>
        <li<% if controller.controller_name == 'users' && controller.action_name != 'totals' %> class="active"<% end %>><%= link_to "Users", users_path %></li>
        <li<% if controller.controller_name == 'users' && controller.action_name == 'totals' %> class="active"<% end %>><%= link_to "Totals", totals_users_path %></li>
      </ul>
    </div>
  </div>
</nav>
<a id="top"></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BorrowApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_subnav.html.erb
<% models_path = send("#{model}s_path") %>
<ul class="subnav nav nav-pills">
  <li role="presentation"<% if controller.action_name == 'index' %> class="active"<%end %>>
  	<%= link_to "Index", models_path %>
  </li>
  <li role="presentation"<% if controller.action_name == 'new' || controller.action_name == 'create' %> class="active"<% end %>>
  	<%= link_to "Create", [:new, model] %>
  </li>
  <li role="presentation"<% if controller.action_name == 'show' %> class="active"<% elsif !defined?(var) %> class="disabled"<% end %>>
  	<% if defined?(var) %><%= link_to "Details", [var] %><% else %><a href="#">Details</a><% end %>
  </li>
  <li role="presentation"<% if controller.action_name == 'edit' %> class="active"<% elsif !defined?(var) %> class="disabled"<% end %>>
  	<% if defined?(var) %><%= link_to "Edit", [:edit, var] %><% else %><a href="#">Edit</a><% end %>
  </li>
  <li role="presentation"<% if controller.action_name == 'delete' %> class="active"<% elsif !defined?(var) %> class="disabled"<% end %>>
  	<% if defined?(var) %><%= link_to "Delete", [var], method: :delete,
      data: { confirm: "Are you sure?" } %><% else %><a href="#">Delete</a><% end %>
  </li>
</ul>

app/views/users/_sums.html.erb
<% if sums.any? %>
  <ul class="list-group">
    <% sums.each do |user, sum| %>
      <li class="list-group-item">
        <%= caption %>
        <span class="borrowing-name"><%= user_link user %></span>:
        <span class="borrow-amount"><%= sum %> EUR</span>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No borrows found.</p>
<% end %>

app/views/users/_user_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, html: { class: "form-horizontal" } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <div class="form-group">
      	<%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
		      <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
		      <%= f.submit @submit_text, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users</h1>

<%= render 'shared/subnav', model: :user, var: @user %>

<% @submit_text = "Update user" %>
<%= render 'user_form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= render 'shared/subnav', model: :user %>

<%= will_paginate @users, class: "pagination-container" %>

<% if @users.any? %>
	<div class="list-group">
	  <% @users.each do |user| %>
	    <a class="list-group-item" href="<%= user_path user %>">
	    	<span class="user-name"><%= user.name %></span>
	    </a>
	  <% end %>
	</div>
<% else %>
  <p>No users found.</p>
<% end %>

<%= will_paginate @users, class: "pagination-container" %>

app/views/users/new.html.erb
<h1>Users</h1>

<%= render 'shared/subnav', model: :user %>

<% @submit_text = "Create user" %>
<%= render 'user_form' %>

app/views/users/show.html.erb
<h1>Users</h1>

<%= render 'shared/subnav', model: :user, var: @user %>

<h2>User details:</h2>
<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @user.name %></dd>
</dl>

<h2>Borrow sums:</h2>
<%= render 'sums', sums: @sums_to, caption: "Borrowed to" %>
<%= render 'sums', sums: @sums_from, caption: "Is borrowing from" %>

<h2>Totals:</h2>
<% if @totals.any? %>
  <ul class="list-group">
    <% @totals.each do |user, sum| %>
      <li class="list-group-item">
        <% if sum > 0 %>
          Borrowed to
          <span class="borrowing-name"><%= user_link user %></span>:
        <% else %>
          Is boworring from
          <span class="borrower-name"><%= user_link user %></span>:
        <% end %>
        <span class="borrow-amount"><%= sum %> EUR</span>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No borrows found.</p>
<% end %>

app/views/users/totals.html.erb
<div class="page-header">
  <h1>Users#totals</h1>
</div>

<h2>Total borrowings:</h2>
<% if @totals.any? %>
  <ul class="list-group">
    <% @totals.each do |user, amount| %>
      <li class="list-group-item">
        <% if amount > 0 %>
          <span class="borrower-name"><%= user_link user %></span> borrowed
          <span class="borrow-amount"><%= amount %> EUR.</span>
        <% else %>
          <span class="borrowing-name"><%= user_link user %></span> is borrowing
          <span class="borrow-amount"><%= -amount %> EUR.</span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No borrows found.</p>
<% end %>

<h2>Suggested solve:</h2>
<% if @solve.any? %>
  <ul class="list-group">
    <% @solve.each do |solve| %>
      <li class="list-group-item">
        <span class="borrower-name"><%= user_link solve[:user_from] %></span> pays
        <span class="borrowing-name"><%= user_link solve[:user_to] %></span>
        <span class="borrow-amount"><%= solve[:amount] %> EUR.</span>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No solves found.</p>
<% end %>